In [2]:
import numpy as np

#将列表转换为数组

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2,2.3,3,4])

In [6]:
b.dtype

dtype('float64')

In [7]:
c = np.array([[1,2,3],[4,5,6]])

In [8]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4),dtype = np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

##empty 用来创建为初始化的随机数数组

In [12]:
np.arange(10,30,5)

array([10, 15, 20, 25])

##创建给定范围内的数组

随机数 NumPy random 模块

In [13]:
np.random.rand(3,2)#0,1均匀分布数组

array([[0.25286629, 0.02366314],
       [0.53487473, 0.18225064],
       [0.59533525, 0.93008358]])

In [14]:
np.random.randint(3,size = 5)

array([1, 2, 0, 2, 1])

In [15]:
?np.random

In [16]:
np.random.randn(3)

array([-2.5322558 , -0.11420633, -2.15194149])

数组的索引与切片

In [3]:
a = np.arange(10)**2 #乘方
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
a[2]

4

In [5]:
a[0]

0

In [15]:
a[0:4] #第一个到第五个不包含第五个 

array([0, 1, 4, 9])

In [9]:
a[:3]#取前三个

array([0, 1, 4])

In [10]:
a[2:]#第三个到完

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
a[::-1] #一维数组翻转

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [22]:
b = np.random.random((3,3))
b

array([[0.39606103, 0.1391618 , 0.33153839],
       [0.71398898, 0.64678951, 0.4605329 ],
       [0.77752481, 0.03176607, 0.5034785 ]])

In [23]:
b[1,2]

0.46053290250116863

In [24]:
b[:3,2] #【开始：第三个，第三列】

array([0.33153839, 0.4605329 , 0.5034785 ])

In [25]:
b[:2,2] #【第一个：第二个，第三列】

array([0.33153839, 0.4605329 ])

In [26]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1:6:3] = 100 #从1号位置开始到6号位置，往后的每第三位令为100
a

array([  0, 100,   2,   3, 100,   5,   6,   7,   8,   9])

In [28]:
a = np.arange(4)
b = np.array([5,10,15,20])

In [29]:
b - a

array([ 5,  9, 13, 17])

In [30]:
b^2

array([ 7,  8, 13, 22])

In [31]:
b**2

array([ 25, 100, 225, 400])

In [32]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [33]:
b < 20

array([ True,  True,  True, False])

In [34]:
np.mean(b)

12.5

In [35]:
np.var(b)

31.25

In [36]:
A = np.array([[1,1],
              [0,1]])

In [37]:
B = np.array([[2,0],
              [3,4]])

In [38]:
A * B

array([[2, 0],
       [0, 4]])

In [39]:
A @ B

array([[5, 4],
       [3, 4]])

In [40]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [42]:
np.linalg.inv(A)

array([[ 1., -1.],
       [ 0.,  1.]])

In [44]:
np.linalg.det(A)

1.0

In [49]:
a = np.floor(10*np.random.random((3,4)))
a

array([[1., 9., 0., 6.],
       [5., 5., 3., 9.],
       [8., 1., 9., 7.]])

In [50]:
a.shape

(3, 4)

In [52]:
a.ravel()

array([1., 9., 0., 6., 5., 5., 3., 9., 8., 1., 9., 7.])

In [53]:
a.reshape(2,6)

array([[1., 9., 0., 6., 5., 5.],
       [3., 9., 8., 1., 9., 7.]])

In [54]:
a.T

array([[1., 5., 8.],
       [9., 5., 1.],
       [0., 3., 9.],
       [6., 9., 7.]])

In [55]:
a.T.shape

(4, 3)

In [56]:
a.reshape(3,-1)

array([[1., 9., 0., 6.],
       [5., 5., 3., 9.],
       [8., 1., 9., 7.]])

In [61]:
print(A)
print(B)
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[1 1 2 0]
 [0 1 3 4]]
[[1 1]
 [0 1]
 [2 0]
 [3 4]]


In [67]:
np.hstack((A,B)).shape

(2, 4)

In [69]:
C = np.arange(16.0)
C

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [70]:
c.dtype

dtype('int64')

In [77]:
c = np.arange(16.0).reshape(4,-1)
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [78]:
np.hsplit(c,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [79]:
np.vsplit(c,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]